### ISSUE TITLE
Clean screen

### ISSUE THREAD

**Issue by thompsonemerson** [maykbrito/screenboard#2]
it would be interesting if there was a command to clear the screen, without having to close and open it again, something like `Cmd+C`.

**Comment by maykbrito** [comment]
I liked it but it's conflicting with system wide copy shortcut :/

**Comment by maykbrito** [comment]
Man I make it wrong. I closed your PR but I liked it. Sorry. My mistake. 

Can you send another using another shortcut? Maybe Ctrl/Cmd +Shift + C?

I've made some code updates too and change some ideas about shortcut. Can you look at that? 

I will love to add your as colab 🥰🥰🚀🚀

**Comment by thompsonemerson** [comment]
all right, i will update and send you another
