### ISSUE TITLE
Teste do screenboard no linux

### ISSUE THREAD

**Issue by luishclaudino** [maykbrito/screenboard#8]
Olá,
Fiz o teste do programa no Linux Ubuntu 18.04.4 LTS e por incrível que pareça aparecia uma tela preta que eu podia desenhar. Continua após as imagens...
![Captura de tela de 2020-05-06 00-22-41](https://user-images.githubusercontent.com/25092787/81135727-ba4c0300-8f2f-11ea-83a4-0e41232b2263.png)
![Captura de tela de 2020-05-06 00-22-45](https://user-images.githubusercontent.com/25092787/81135744-c1731100-8f2f-11ea-9cff-277b78100bd9.png)

Tentei mexer em um monte de coisa com relação a opacidade e nada resolvia. Procurando na internet vi pessoas com o mesmo problema e uma solução que achei e deu certo foi a seguinte:
https://github.com/electron/electron/issues/16809

Resultado:
![Captura de tela de 2020-05-06 00-26-19](https://user-images.githubusercontent.com/25092787/81135977-89200280-8f30-11ea-8fe0-fb403bec0665.png)

Então eu fiz algumas modificações para tirar as barras de rolagem (um problema que ocorre pois a barras laterais diminuem a tela e você pega medidas da tela como um todo), além disso criei comandos para minimizar e maximizar o screenboard(Ctrl+F11) e para limpar a tela (Ctrl + C)
Segue o meu repositório com as modificações:
https://github.com/luishclaudino/screenboard-for-linux

**Comment by tiagopaes** [comment]
Não seria uma boa criar um pull request com suas alterações? O que acha @maykbrito ?

**Comment by cl4udino** [comment]
@tiagopaes vou fazer um fork, fazer as alterações e mandar o pull request.

**Comment by cl4udino** [comment]
Como aparece no meu vídeo https://youtu.be/a51h5hOC7ic , o comando `Ctrl + w` não só fecha a janela como mata a aplicação no Linux. Assim, não é possível reabrir com `Ctrl + Shift + w`, tendo que dar `npm start` para reabri-lo. Com o comando de hide (`Ctrl + Shift + H`) é possível, mantê-lo aberto. Feature foi enviada no PR #19 e aguardando aprovação.

**Comment by maykbrito** [comment]
Olá amigos!

Eu fiz uma baita alteração no projeto, usando referências de outra libs e outras dependências. 

Estou fechando esta issue para que possamos focar em novas!

Obrigado a cada um 💜
